"""Provisional, replaceable write-time admission research framework."""

from memoryrush.admission.decision import (
    AdmissionResult,
    ConservativeDecisionPolicy,
    DecisionPolicy,
    PerturbationAudit,
    evaluate_admission,
)
from memoryrush.admission.evaluation import (
    EvaluationSummary,
    MatchedAdmissionResult,
    MethodPrediction,
    evaluate_predictions,
    matched_admission_evaluation,
)
from memoryrush.admission.experiment_runner import (
    CURRENT_ID_ONLY,
    EXACT_COPY,
    ID_ONLY_PROXY,
    STATIC_ORACLE_UPPER_BOUND,
    ArtifactValidationStatus,
    ExperimentArtifact,
    ExperimentConfig,
    FrozenBenchmark,
    InvalidExperimentArtifact,
    MethodExperimentResult,
    RunClass,
    artifact_to_dict,
    build_invalid_experiment_artifact,
    load_frozen_benchmark,
    run_direction1_experiment,
    run_method_predictions,
    write_experiment_artifact,
)
from memoryrush.admission.models import (
    AdmissionDecision,
    AtomicClaim,
    CandidateClaim,
    ClaimFormAudit,
    ClaimFormStatus,
    EvidenceSpan,
    QualifierKind,
    QualifierSlot,
    SupportCell,
    SupportLabel,
    SupportMatrix,
)
from memoryrush.admission.protocols import Verifier
from memoryrush.admission.perturbations import CandidatePerturbation, replace_qualifier
from memoryrush.admission.solver import (
    DeletionAudit,
    DeletionTrial,
    EvidenceSetSolver,
    EvidenceSolution,
    InclusionMinimalSolver,
    MinimumCardinalitySolver,
    SufficiencyResult,
    audit_evidence_deletions,
    evaluate_sufficiency,
)
from memoryrush.admission.verifiers import ExactCopyVerifier, IdOnlyVerifier, StaticOracleVerifier

__all__ = [
    "AdmissionDecision",
    "AdmissionResult",
    "ArtifactValidationStatus",
    "AtomicClaim",
    "CandidateClaim",
    "CandidatePerturbation",
    "ClaimFormAudit",
    "ClaimFormStatus",
    "ConservativeDecisionPolicy",
    "CURRENT_ID_ONLY",
    "DeletionAudit",
    "DeletionTrial",
    "DecisionPolicy",
    "EvidenceSpan",
    "EXACT_COPY",
    "EvaluationSummary",
    "ExperimentArtifact",
    "ExperimentConfig",
    "EvidenceSetSolver",
    "EvidenceSolution",
    "InclusionMinimalSolver",
    "ExactCopyVerifier",
    "IdOnlyVerifier",
    "ID_ONLY_PROXY",
    "MinimumCardinalitySolver",
    "MatchedAdmissionResult",
    "MethodPrediction",
    "MethodExperimentResult",
    "PerturbationAudit",
    "QualifierKind",
    "QualifierSlot",
    "SupportCell",
    "SupportLabel",
    "SupportMatrix",
    "StaticOracleVerifier",
    "STATIC_ORACLE_UPPER_BOUND",
    "SufficiencyResult",
    "Verifier",
    "FrozenBenchmark",
    "InvalidExperimentArtifact",
    "RunClass",
    "artifact_to_dict",
    "audit_evidence_deletions",
    "evaluate_admission",
    "evaluate_predictions",
    "evaluate_sufficiency",
    "matched_admission_evaluation",
    "build_invalid_experiment_artifact",
    "load_frozen_benchmark",
    "replace_qualifier",
    "run_direction1_experiment",
    "run_method_predictions",
    "write_experiment_artifact",
]
